Past rides
370phoenix/phoenix pull request #38
Opened 2023-04-18 18:50 UTC by Sessenfeld

## Describe your changes

## This PR is for:

- [x] User Story/Feature
- [x] Bug fix
- [ ] Refactoring
- [ ] Maintenance

## Issue ticket number and link (Jira) 107

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing unit tests pass locally with my changes

2023-04-19 04:21 UTC, willtheodore requested changes

2023-04-19 04:21 UTC, willtheodore commented on constants/DataTypes.ts
> +export type UserID = string;
delete this file

2023-04-19 04:21 UTC, willtheodore commented on utils/auth.ts
> +import { PostID } from "../constants/DataTypes";
remove

2023-04-19 04:21 UTC, willtheodore commented on components/posts/PastPostsCard.tsx
> +export type Props = {
don't export this type

2023-04-19 04:21 UTC, willtheodore commented on navigation/Header.tsx
> +        width: 30,
why is this added?

2023-04-19 04:21 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +import { RootStackParamList } from "../../types";
clean up these imports

2023-04-19 04:21 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +    //if (!post) return <></>;
remove these comments

2023-04-19 04:21 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +    const onSubmit = useState<string>;
useState shouldn't be used this way

2023-04-19 04:21 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +    //const [buttonColor, setButtonColor] = useState({color: "purple"});
remove

2023-04-19 04:21 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +        //setButtonColor({color: "gray"});
get rid off all these comments that aren't needed

2023-04-19 04:21 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +function UserList({
move to separate file

2023-04-19 04:21 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +function UserDetails({ user, num, post }: { user: UserInfo; num: number; post: PostType }) {
move to separate file

2023-04-19 04:21 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +function MoreInfo({ post }: { post: PostType }) {
move to separate file

2023-04-19 04:21 UTC, willtheodore commented on types.tsx
> +    //MatchDetails: MatchDetailsParamList | undefined;
why is this comment here

2023-04-19 04:21 UTC, willtheodore commented on utils/feedback.ts
> +        // const fbID = fbRef.key;
delete these comments

2023-04-19 04:21 UTC, willtheodore commented on utils/machines/multiplePostsMachine.ts
> +import { PostType } from "../../constants/DataTypes";
is this machine being used anywhere? It's showing up as a new file

2023-04-19 15:08 UTC, alkersha commented on types.tsx
> +    //MatchDetails: MatchDetailsParamList | undefined;
We were getting errors with MatchDetails not existing. Not sure if you guys needed it for a different branch.

2023-04-20 01:08 UTC, Sessenfeld commented on constants/DataTypes.ts
> +export type UserID = string;
done

2023-04-20 01:09 UTC, Sessenfeld commented on utils/auth.ts
> +import { PostID } from "../constants/DataTypes";
done

2023-04-20 01:09 UTC, Sessenfeld commented on components/posts/PastPostsCard.tsx
> +export type Props = {
so just delete it then? if so, done

2023-04-20 01:58 UTC, Sessenfeld commented on navigation/Header.tsx
> +        width: 30,
we were trying to make the openBook a bigger icon, i just retried this and it does not seem to affect the book, may add this back later but prob not

done

2023-04-20 01:59 UTC, Sessenfeld commented on screens/modals/PastPostDetailsScreen.tsx
> +import { RootStackParamList } from "../../types";
done

delete these unused imports:
import { matchPost } from "../../utils/posts";
import { Right } from "../../assets/icons/Arrow";
import RoundTrip from "../../assets/icons/RoundTrip";

2023-04-20 02:05 UTC, Sessenfeld commented on screens/modals/PastPostDetailsScreen.tsx
> +    //if (!post) return <></>;
done

2023-04-20 02:05 UTC, Sessenfeld commented on screens/modals/PastPostDetailsScreen.tsx
> +    //const [buttonColor, setButtonColor] = useState({color: "purple"});
done

2023-04-20 02:05 UTC, Sessenfeld commented on screens/modals/PastPostDetailsScreen.tsx
> +        //setButtonColor({color: "gray"});
done

2023-04-20 02:07 UTC, Sessenfeld commented on utils/feedback.ts
> +        // const fbID = fbRef.key;
done

2023-04-20 03:03 UTC, Sessenfeld commented on utils/machines/multiplePostsMachine.ts
> +import { PostType } from "../../constants/DataTypes";
doesnt look like it, want me to delete the machine?

2023-04-20 03:04 UTC, Sessenfeld commented on components/posts/PastPostsCard.tsx
> +export type Props = {
is there a prop instead we should export? we use this in line 16

2023-04-20 03:08 UTC, Sessenfeld commented on screens/modals/PastPostDetailsScreen.tsx
> +    const onSubmit = useState<string>;
so then what kind of parameter does useState require in this context, if not a string? just trying to understand

2023-04-20 05:40 UTC, Sessenfeld commented on screens/modals/PastPostDetailsScreen.tsx
> +function UserList({
what folder should this file be in?

2023-04-20 05:40 UTC, Sessenfeld commented on screens/modals/PastPostDetailsScreen.tsx
> +function UserDetails({ user, num, post }: { user: UserInfo; num: number; post: PostType }) {
what folder should this file be in?

2023-04-20 05:40 UTC, Sessenfeld commented on screens/modals/PastPostDetailsScreen.tsx
> +function MoreInfo({ post }: { post: PostType }) {
what folder should this file be in?

2023-04-20 05:47 UTC, willtheodore requested changes

2023-04-20 05:47 UTC, willtheodore commented on components/posts/PastPostsCard.tsx
> +    //what do we use instead of props?
no use props! You just don't want to export it.

2023-04-20 05:47 UTC, willtheodore commented on navigation/index.tsx
> +// import PastPostDetailsScreen from "../screens/modals/PastPostDetailsScreen"; //these arent used in this file?
delete

2023-04-20 05:47 UTC, willtheodore commented on screens/modals/MoreInfo.tsx
> +//NOTE: SHOULD THIS FILE BE HERE OR IN ANOTHER SECTION? THIS FILE IS IN THIS LOCATION TEMPORARILY
move to components folder.

2023-04-20 05:47 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +import { RootStackParamList } from "../../types";
don't leave stuff commented out. Just delete it.

2023-04-20 05:47 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +    const onSubmit = useState<string>;
You're not passing a string there. Notation like<this> is for generic types in typescript. To call useState, you need to use parens like this: `useState()` Also, "onSubmit" is a naming  convention typically used for functions, instead of strings. It makes it somewhat confusing to read, and you should rename the variable

2023-04-20 05:47 UTC, willtheodore commented on screens/modals/PastPostDetailsScreen.tsx
> +    const onSubmit = useState<string>;
Also, the return type of `useState` is a tuple, like in setNotes. So the notes part is totally fine its the onSubmit that is weird.

2023-04-20 05:47 UTC, willtheodore commented on screens/modals/UserDetails.tsx
> +//NOTE: SHOULD THIS FILE BE HERE OR IN ANOTHER SECTION? THIS FILE IS IN THIS LOCATION TEMPORARILY
move to components folder

2023-04-20 05:47 UTC, willtheodore commented on screens/modals/UserList.tsx
> +//NOTE: SHOULD THIS FILE BE HERE OR IN ANOTHER SECTION? THIS FILE IS IN THIS LOCATION TEMPORARILY
move to components folder

2023-04-20 05:47 UTC, willtheodore commented on utils/feedback.ts
> +import { SuccessMessage, ErrorMessage, MessageType } from "./auth"; //didnt we get rid of this?
yes, delete it.

2023-04-20 05:47 UTC, willtheodore commented on utils/feedback.ts
> +    feedback: FeedbackEntryType //need to make this different?
Just redefine the type in this file.

2023-04-20 05:48 UTC, willtheodore commented on utils/machines/multiplePostsMachine.ts
> +import { PostType } from "../../constants/DataTypes";
yes, delete it

2023-04-20 05:49 UTC, willtheodore commented on types.tsx
> +    //MatchDetails: MatchDetailsParamList | undefined;
If it isn't used anywhere in navigation/index.tsx, delete it. Otherwise, make sure it isn't commented out.

2023-04-20 05:52 UTC, Sessenfeld commented on types.tsx
> +    //MatchDetails: MatchDetailsParamList | undefined;
it was not being used anywhere in index, it has now been deleted

2023-04-20 05:53 UTC, Sessenfeld commented on utils/machines/multiplePostsMachine.ts
> +import { PostType } from "../../constants/DataTypes";
deleted the machine

2023-04-20 05:55 UTC, Sessenfeld commented on components/posts/PastPostsCard.tsx
> +    //what do we use instead of props?
ohhhhhh, resolved

2023-04-20 05:56 UTC, Sessenfeld commented on navigation/index.tsx
> +// import PastPostDetailsScreen from "../screens/modals/PastPostDetailsScreen"; //these arent used in this file?
done

2023-04-20 06:02 UTC, Sessenfeld commented on screens/modals/MoreInfo.tsx
> +//NOTE: SHOULD THIS FILE BE HERE OR IN ANOTHER SECTION? THIS FILE IS IN THIS LOCATION TEMPORARILY
done

2023-04-20 06:18 UTC, Sessenfeld commented on screens/modals/UserDetails.tsx
> +//NOTE: SHOULD THIS FILE BE HERE OR IN ANOTHER SECTION? THIS FILE IS IN THIS LOCATION TEMPORARILY
done

2023-04-20 06:18 UTC, Sessenfeld commented on screens/modals/UserList.tsx
> +//NOTE: SHOULD THIS FILE BE HERE OR IN ANOTHER SECTION? THIS FILE IS IN THIS LOCATION TEMPORARILY
done

2023-04-20 06:19 UTC, Sessenfeld commented on utils/feedback.ts
> +import { SuccessMessage, ErrorMessage, MessageType } from "./auth"; //didnt we get rid of this?
but then doesnt the promise in line 10 get messed up?

2023-04-20 06:19 UTC, Sessenfeld commented on utils/feedback.ts
> +    feedback: FeedbackEntryType //need to make this different?
to TouchableNativeFeedback or something else?

2023-04-20 06:30 UTC, Sessenfeld commented on screens/modals/PastPostDetailsScreen.tsx
> +    const onSubmit = useState<string>;
lines 34 and 35 arent used so i deleted them anyways

2023-04-20 13:57 UTC, willtheodore commented on utils/feedback.ts
> +import { SuccessMessage, ErrorMessage, MessageType } from "./auth"; //didnt we get rid of this?
Yeah you should rewrite that so that it doesn't have a try catch and just throws an error. It will still be a promise because it's async, but you'll just return void.

2023-04-20 19:41 UTC, willtheodore approved these changes

2023-04-20 19:41 UTC, merged